In [1]:
import torch
import numpy as np
torch.manual_seed(1234)

def describe(x):
    print("# Describe :::")
    print(f"Type: {x.type()}")
    print(f"Shape/size: {x.shape}")
    print(f"Values: \n{x}")
    print("==========================")

# Tensor 타입

Tensor의 기본 타입은 `FloatTensor` 이다.

In [2]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)

# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [3]:
x = torch.randn(2, 3)
describe(x)

x = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6]])
describe(x)

x = x.long()
describe(x)

x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

x = x.float() 
describe(x)

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
x = torch.randn(2, 3)
describe(x)
describe(torch.add(x, x))  # 행렬 덧셈 : x 와 x를 행렬 덧셈 연산한다.

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])
# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4619,  1.3862, -0.5337],
        [ 4.3569,  0.2043, -0.5180]])


In [7]:
# torch.add(x, x) 와 같은 결과.
describe(x + x)

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4619,  1.3862, -0.5337],
        [ 4.3569,  0.2043, -0.5180]])


In [9]:
x = torch.arange(6)  # 1차원 Vector 형태의 Tensor로 생성.
describe(x)

x = x.view(2, 3)  # 2행 3열 형식으로 변경
describe(x)

# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [10]:
describe(torch.sum(x, dim=0))  # dim=0 : "열" 끼리 더한다. (세로로)
describe(torch.sum(x, dim=1))  # dim=1 : "행" 끼리 더한다. (가로로)
describe(torch.transpose(x, 0, 1))  # 주대각선을 긋고, 주대각선을 기준으로 회전 시킨(행과 열을 교환한) 전치행렬을 얻어낸다.

# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [12]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)
describe(x[:1, :2])
describe(x[0, 1])

# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


## `view()` 에 대해

- view()는 포인터 같은 녀석이다.
- 위 예제에서는 `x`와 `vx`의 주소 값이 같은것을 확인할 수 있다.

```python
import torch
x = torch.arange(6)
vx = x.view(2, 3)
print(x.data_ptr())  # data_ptr() => 데이터 주소 가져오기
print(vx.data_ptr())
```

## 코드 설명 : `torch.index_select(x, dim=1, index=indeces)`
- `LongTensor([0, 2])` 를 통해, [0번, 2번] 인덱스들(말 그대로 indeces)을 생성했음.
  - `x` 라는 2차원 배열에서 `[0번, 2번]` 인덱스들을 가져온다는 의미이다.
- `dim=1` : 2차원 배열에서 dim=1은 "열"(컬럼)을 의미한다.
- `index=indeces` : 가져올 인덱스(들) 설정값을 할당해준다.
  - 따라서, `x` 배열의 0번, 2번 컬럼 값을 가져온다.  

In [11]:
indeces = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indeces))

# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [22]:
indeces = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indeces))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


## 코드 설명 : `x[[0, 1], [0, 1]]`

`x[0, 0]` , `x[1, 1]` 값 2개를 담고 있는 배열을 리턴한다.

> 팁 : Index에 사용하는 Tensor 는 전부 `Long` 타입이다. 따라서, 인덱스에 `LongTensor`를 사용하지 않으면 에러 발생함.
> > But, `Int`는 예외적으로 가능.

In [16]:
row_indeces = torch.arange(2).long()  # arange(2): [0, 1] 리턴 / long(): Long 타입으로 리턴
col_indeces = torch.LongTensor([0, 1])
print(row_indeces)
describe(x)
print("=====")
describe(x[row_indeces, col_indeces])

tensor([0, 1])
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
=====
# Describe :::
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


> LongTensor: int64
> 
> IntTensor: int32

In [27]:
x = torch.LongTensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
describe(x)
print(x.dtype)  # LongTensor: int64 / IntTensor: int32
print(x.numpy().dtype)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
int64


In [26]:
x = torch.arange(0, 20)

print(x.view(1, 20))
print(x.view(2, 10))
print(x.view(4, 5))
# print(x.view(10, 1))  # error 발생. 데이터가 20개인데 10개밖에 안나오는 형식이라서..
print(x.view(20, 1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])


## Tensor 배열 연산

> 아래 코드 설명

`print(x + y)` : `x`와 `y`는 "열"의 개수가 같으므로, 각 열에 대응되는 값을 더할 수 있음.

`print(x + z)` : `x`와 `z`는 "행"의 개수가 같으므로, 각 행에 대응되는 값을 더할 수 있음.

In [32]:
x = torch.arange(12).view(3, 4)
y = torch.arange(4).view(1, 4)
z = torch.arange(3).view(3, 1)

print(x)
print(y)
print(z)

print(x + y)
print(x + z)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3]])
tensor([[0],
        [1],
        [2]])
tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])
tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])


## `squeeze()` 와 `unsqueeze(dim=)`

- `squeeze`: 차원 하나를 **"제거"** 한다.
- `unsqeeze(dim=n)`: 차원 n개를 **"추가"** 한다.

In [33]:
x = torch.arange(12).view(3, 4)
describe(x)

x = x.unsqueeze(dim=1)
describe(x)

x = x.squeeze()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Type: torch.LongTensor
Shape/size: torch.Size([3, 1, 4])
Values: 
tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])
Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
