# PyTorch Basics

In [1]:
import torch
import numpy as np
torch.manual_seed(1234)  # 수동으로 Seed값 할당

## Tensors

* Scalar is a single number.
* Vector is an array of numbers.
* Matrix is a 2-D array of numbers.
* Tensors are N-D arrays of numbers.

#### Creating Tensors

You can create tensors by specifying the shape as arguments.  
Here is a tensor with 2 rows and 3 columns

Tensor의 정보를 요약해서 보여주는 함수를 미리 만들어놓고 앞으로 계속 쓸거임.

In [2]:
def describe(x):
    print("# Describe :::")
    print(f"Type: {x.type()}")
    print(f"Shape/size: {x.shape}")
    print(f"Values: \n{x}")
    print("==========================")

In [7]:
# 2행 3열 Tensor 생성
describe(torch.Tensor(2, 3))

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 랜덤한 Tensor 만들기

It's common in prototyping to create a tensor with random numbers of a specific shape.  
특정 크기의 랜덤한 텐서를 만드는 것이 일반적이다.

- `torch.randn(x, y)` : x행 y열 사이즈의 **표준 정규 분포** 를 갖고 있는 **랜덤 Tensor 생성**
- `torch.rand(x, y)` : x행 y열 사이즈의 **일항 분포(또는 균등 분포)** 를 갖고 있는 **랜덤 Tensor 생성**

> 표준 정규 분포 : 평균이 0이고 분산이 1인 정규 분포

In [3]:
# 2행 3열 사이즈의 표준 정규 분포를 갖고 있는 Tensor 생성
describe(torch.randn(2, 3))

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [4]:
# `randn`이 "표준 정규 분포"라면, `rand`는 "일항 분포"(또는 "균등 분포")임.
x = torch.rand(2, 3)
describe(x)

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])


You can also initialize tensors of ones or zeros.  
0 또는 1로, 또는 원하는 값으로 채워진 Tensor 만들기

Note: operations that end in an underscore (`_`) are in place operations.  
메모: 언더스코어로 끝나는 함수들은 `"제자리 연산"` 이다. (해당 레퍼런스에 직접 접근해서 값을 바꿔버리는)

In [12]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
# Describe :::
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


Tensors can be initialized from a list of lists  
형식을 미리 지정해서 초기화도 할 수 있음.

In [7]:
x = torch.Tensor([[1, 2,],  
                  [2, 4,]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 2.],
        [2., 4.]])


Tensors can be initialized from numpy matrices  
넘파이 매트릭스를 넣어서 torch를 만들수도 있음.

In [10]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))
print(npy.dtype)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.6938, 0.0125, 0.7894],
        [0.4493, 0.1734, 0.4403]], dtype=torch.float64)
float64
